import { InjectedConnector } from '@web3-react/injected-connector'

/**
 * 所有的chaingId 集合
 */
export const chainIds = {
  MAINNET: 1,
  ROPSTEN: 3,
  RINKEBY: 4,
  GÖRLI: 5,
  KOVAN: 42,
  BSC: 56,
  BSC_TESTNET: 97,
  MATIC: 137,
  MATIC_TESTNET: 80001,
  FANTOM: 250,
  FANTOM_TESTNET: 4002,
  XDAI: 100,
  ARBITRUM: 42161,
  ARBITRUM_TESTNET: 79377087078960,
  MOONBEAM_TESTNET: 1287,
  AVALANCHE: 43114,
  AVALANCHE_TESTNET: 43113,
  FUJI: 43113,
  HECO: 128,
  HECO_TESTNET: 256,
  HARMONY: 1666600000,
  HARMONY_TESTNET: 1666700000,
  OKEX: 66,
  OKEX_TESTNET: 65,
  CELO: 42220,
  PALM: 11297108109,
  PALM_TESTNET: 11297108099,
  MUMBAI: 80001,
  FUSE: 122,
  FUSE_TESTNET: 121,
  AUTHEREUM: 246,
  AUTHEREUM_TESTNET: 245,
  MOONRIVER: 1285,
  MOONRIVER_TESTNET: 1287,
  AQUA: 61717561,
  AQUA_TESTNET: 61717560,
  SHIBA: 0x61,
  SHIBA_TESTNET: 0x62,
  BSC_GOV: 0x38,
  BSC_GOV_TESTNET: 0x61,
}

// TODO 部分网络不支持 需去除
export const injected = new InjectedConnector({
  supportedChainIds: [
    chainIds.MAINNET,
    chainIds.ROPSTEN,
    chainIds.RINKEBY,
    chainIds.GÖRLI,
    chainIds.KOVAN,
    chainIds.BSC,
    chainIds.BSC_TESTNET,
    chainIds.MATIC,
    chainIds.MATIC_TESTNET,
    chainIds.FANTOM,
    chainIds.FANTOM_TESTNET,
    chainIds.XDAI,
    chainIds.ARBITRUM,
    chainIds.ARBITRUM_TESTNET,
    chainIds.MOONBEAM_TESTNET,
    chainIds.AVALANCHE,
    chainIds.AVALANCHE_TESTNET,
    chainIds.FUJI,
    chainIds.HECO,
    chainIds.HECO_TESTNET,
    chainIds.HARMONY,
    chainIds.HARMONY_TESTNET,
    chainIds.OKEX,
    chainIds.OKEX_TESTNET,
    chainIds.CELO,
    chainIds.PALM,
    chainIds.PALM_TESTNET,
    chainIds.MUMBAI,
    chainIds.FUSE,
    chainIds.FUSE_TESTNET,
    chainIds.AUTHEREUM,
    chainIds.AUTHEREUM_TESTNET,
    chainIds.MOONRIVER,
    chainIds.MOONRIVER_TESTNET,
    chainIds.AQUA,
    chainIds.AQUA_TESTNET,
    chainIds.SHIBA,
    chainIds.SHIBA_TESTNET,
    chainIds.BSC_GOV,
    chainIds.BSC_GOV_TESTNET,
  ],
})

